version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk11
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
  - mvn install -B -DskipTest
  - mvn package -B -DskipTest -f example\pom.xml
test_script:
  - mvn test -B
  - mvn test -B -f example\pom.xml
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
