version: '{build}'
os: Windows Server 2012
build_script:
  - mvn install -B -DskipTest
  - mvn package -B -DskipTest -f example\pom.xml
test_script:
  - mvn test -B
  - mvn test -B -f example\pom.xml
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
